version: '3.9'

services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: treemenu
      POSTGRES_USER: treemenu
      POSTGRES_PASSWORD: securepassword
    ports:
      - "5432:5432"

  web:
    build: .
    command: bash -c "python manage.py migrate && gunicorn --bind 0.0.0.0:8000 tree_menu_project.wsgi"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://treemenu:securepassword@db:5432/treemenu
    depends_on:
      - db

volumes:
  postgres_data: